Repository uniS2/FESP01-TodoApp-Project10, pull requests merged in 2023-11, with the labels that each got.

#12 style: css 분리
  02.typescript/src/index.css
  02.typescript/src/pages/regist/TodoRegist.css
Labels: 💻Feature

#13 refactor : TodoList.ts 타입 지정
  02.typescript/api/db/todolist.json
  02.typescript/api/package-lock.json
  02.typescript/package-lock.json
  02.typescript/src/pages/list/TodoList.ts
  package-lock.json
  package.json
Labels: 💻Feature, 2️⃣TEAM

#15 Refactor: axios 모듈화
  02.typescript/src/API/axios.ts
  02.typescript/src/pages/regist/TodoRegist.ts
Labels: 💻Feature, 1️⃣TEAM
