Repository uniS2/FESP01-TodoApp-Project10, pull requests merged in 2023-10, with the labels that each got.

#5 Detail page CSS 완성했습니다.
  01.javascript/todoapp/assets/css/index.css
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
Labels: 💻Feature, 1️⃣TEAM

#6 [feat, style] enroll버튼 추가, css 추가
  01.javascript/todoapp/assets/css/index.css
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
Labels: 💻Feature, 2️⃣TEAM

#8 README 수정
  01.javascript/todoapp/README.md
  README.md
  todo.png
Labels: 📑Docs, 💻Feature, 2️⃣TEAM

#9 [feat] 등록 및 할일 완료 기능 구현
  01.javascript/todoapp/assets/css/index.css
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
  01.javascript/todoapp/index.html
Labels: 💻Feature, 1️⃣TEAM

#10 [feat] : 최종 작업 완료
  01.javascript/todoapp/README.md
  01.javascript/todoapp/api/db/initData.js
  01.javascript/todoapp/assets/css/index.css
  01.javascript/todoapp/assets/js/App.js
  01.javascript/todoapp/assets/js/Router.js
  01.javascript/todoapp/assets/js/pages/info/TodoInfo.js
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
  01.javascript/todoapp/index.html
  README.md
  todo.png
  todoRegist.png
Labels: 📑Docs, 💻Feature
